In [4]:
import numpy as np

>**numpy array**

In [5]:
l1 = [20, 30, 40]

In [6]:
np.array(l1)

array([20, 30, 40])

In [7]:
l2 = [[10, 20], [30, 40], [50, 60]]

In [8]:
np.array(l2)

array([[10, 20],
       [30, 40],
       [50, 60]])

>**arange**

In [9]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

>**zeros / ones**

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

>**linspace**

In [16]:
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [17]:
np.linspace(0, 10, 16)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

>**eye**

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

>**random**

In [19]:
np.random.randn(5)

array([ 0.00916537,  1.23592263,  2.24163494, -0.47901056,  0.8266165 ])

In [20]:
np.random.randn(3,3)

array([[-1.19201347, -0.67075237,  0.63923739],
       [ 0.48613695, -0.88860004, -0.52768729],
       [ 1.31458439, -0.52832719, -0.31310224]])

In [21]:
np.random.randint(5)

1

In [22]:
np.random.randint(1, 10)

1

In [23]:
np.random.randint(1, 10, 3)

array([2, 4, 7])

In [24]:
np.random.randint(1, 300, 3)

array([248, 120, 147])

In [25]:
d1 = np.arange(30)
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
d2 = np.random.randint(0, 100, 10)
d2

array([74, 61, 21,  1, 60,  6,  8, 67, 36, 16])

>**numpy dizi methodları**

In [27]:
d1.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [28]:
d1.max()

29

In [29]:
d1.min()

0

In [30]:
d1.argmax()

29

In [31]:
d1.argmin()

0

In [32]:
d2 = d1.reshape(5,6)
d2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [33]:
d1[5]

5

In [34]:
d1[4:9]

array([4, 5, 6, 7, 8])

In [35]:
d1[4:9:2]

array([4, 6, 8])

In [36]:
d1[4:9] = 50

In [37]:
d1

array([ 0,  1,  2,  3, 50, 50, 50, 50, 50,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
d3 = np.arange(1,21)
d3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
silicingDizisi = d3[5:10]

In [40]:
silicingDizisi

array([ 6,  7,  8,  9, 10])

In [41]:
silicingDizisi[:] = 700
silicingDizisi

array([700, 700, 700, 700, 700])

In [42]:
d3

array([  1,   2,   3,   4,   5, 700, 700, 700, 700, 700,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [43]:
d4 = np.arange(1, 21)
d4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
d4kopya = d4.copy()

In [45]:
d4kopyaSilicing = d4kopya[3:6]
d4kopyaSilicing

array([4, 5, 6])

In [46]:
d4kopyaSilicing[:] = 800
d4kopyaSilicing

array([800, 800, 800])

In [47]:
d4kopya

array([  1,   2,   3, 800, 800, 800,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [48]:
d4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

>**matrix**

In [49]:
l2 = [[10, 20, 30], [20, 30, 40], [40, 50, 60]]

In [50]:
matrix = np.array(l2)
matrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [51]:
matrix[0]

array([10, 20, 30])

In [52]:
matrix[0][1]

20

In [53]:
matrix[0, 1]

20

In [55]:
matrix[0:, 1] #0. indexten başlar yani ilk satırdan daha sonra her satırın 1. indexini alır

array([20, 30, 50])

In [56]:
matrix[2:, 2:]

array([[60]])

In [57]:
l3 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [60]:
l3 = np.array(l3)
l3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [61]:
l3[2]

array([ 9, 10, 11, 12])

In [63]:
l3[[0,2,3]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

>**operasyonlar**

In [68]:
dizi = np.random.randint(1, 100, 20)
dizi

array([87, 73, 79, 44, 45, 31, 20, 77, 34, 73, 30, 53, 45, 36, 30, 13, 88,
       22, 82, 46])

In [69]:
dizi.max()

88

In [70]:
dizi > 24

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [71]:
sonucDizi = dizi > 24

In [72]:
sonucDizi

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True])

In [73]:
dizi[sonucDizi]

array([87, 73, 79, 44, 45, 31, 77, 34, 73, 30, 53, 45, 36, 30, 88, 82, 46])

In [74]:
dizi[dizi > 24]

array([87, 73, 79, 44, 45, 31, 77, 34, 73, 30, 53, 45, 36, 30, 88, 82, 46])

In [76]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [78]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [79]:
sonDizi / sonDizi

/var/folders/9g/5bgf0gcn7f755k1kh7ljlmxr0000gn/T/ipykernel_35569/1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [80]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [81]:
np.min(sonDizi)

0